#!/bin/bash

##############################################
### "Simple" backup script using rsync
### Backs up the contents of BDRI to a timestamped directory in DDIR
### Designed to be able to be run manually or with a cron job
##############################################

# directory for backup - /./ is included for -R option
#BDIR='/srv/share/./'
SHAREDIR="/srv/share/"
BDIR1='/var/./www/'
BDIR2='/etc/'
BDIR3='/home/'
# dir to backup
BACKUP_DIR='/media/ironwolf1/backups/'
DDIR=$BACKUP_DIR'kragle/'
# date files
DATE1=${DDIR}'date.txt'
DATE2=${DDIR}'date2.txt'
# excluded directories -- currently other backups
EXCLUDES='./exclude.txt'
# make top level backup dir if it doesn't already exist
CURRENT_DIR=`pwd`
cd $BACKUP_DIR
mkdir $DDIR
cd $CURRENT_DIR

# copy old date file - yes is used to confirm copy
# touch and mkdir is used in case the files don't exist yet
touch $DATE1
touch $DATE2
yes | cp $DATE1 $DATE2
# create new date file
echo `date +"%F"` > $DATE1

# create log file
LOGFILE=$DDIR'rsync-'`cat $DATE1`'.log'
touch $LOGFILE
echo "" > $LOGFILE

#################################################
# This is where the magic happens
#################################################

# (don't) compress
# zip is used before sync, because it retains file structure,
# allowing for incremental backup
#zip /srv/samba/share.zip /srv/samba/share/

# kill any running rsync tasks
# (if you don't do this, things can break)
pkill -9 rsync

# backup files
rsync -avhPR --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --stats --exclude-from=${EXCLUDES} --log-file=$LOGFILE --link-dest=${DDIR}Backup-`cat $DATE2` "$SHAREDIR" ${DDIR}Backup-`cat $DATE1`/

rsync -avhPR --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --stats --exclude-from=${EXCLUDES} --log-file=$LOGFILE --link-dest=${DDIR}Backup-`cat $DATE2` $BDIR1 ${DDIR}Backup-`cat $DATE1`/

rsync -avhPR --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --stats --exclude-from=${EXCLUDES} --log-file=$LOGFILE --link-dest=${DDIR}Backup-`cat $DATE2` $BDIR2 ${DDIR}Backup-`cat $DATE1`/

rsync -avhPR --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --stats --exclude-from=${EXCLUDES} --log-file=$LOGFILE --link-dest=${DDIR}Backup-`cat $DATE2` $BDIR3 ${DDIR}Backup-`cat $DATE1`/

# Options:
# a : preserve groups, perms, times, etc
# v : verbose
# h : human-redable; sizes are in KB/MB/GB rather than bytes
# P : combines --partial and --progress which are both useful for long xfers;
#   : --partial allows large transfers to continue across interuption
#   : --progress prints the progress of each file
# R : relative; preserves the whole path, except for anything higher than /./
# --chmod : set permmisions for the new directory
# --stats : logs stats about the xfer
# --exclude-from : path to exclude file, which contains string search terms to exclude from backup
# --log-file : file to store log to, can be useful for review
# --link-dest : creates hard links for unchanged files in the current increment 
#             : to their last change, allowing single-step restore

# copy log file into backup dir
mv $LOGFILE ${DDIR}Backup-`cat $DATE1`

# add list of installed programs with apt
apt list --installed | awk '{split($0, a, "/"); print a[1]}' > ${DDIR}Backup-`cat $DATE1`/apt-list.txt
